### ISSUE TITLE
Support for Global Accelerator resource

### ISSUE THREAD

**Issue by pl-philips** [zenlayer/terraform-provider-zenlayercloud#2]
Hello,

it seems that the support for Global Accelerator [resource is missing](https://registry.terraform.io/providers/zenlayer/zenlayercloud/latest/docs). Do you have any plan on the roadmap to add support for it?

Thanks!

**Comment by wolfgangzhu** [comment]
> Hello,
> 
> it seems that the support for Global Accelerator [resource is missing](https://registry.terraform.io/providers/zenlayer/zenlayercloud/latest/docs). Do you have any plan on the roadmap to add support for it?
> 
> Thanks!

Currently, there are no plans to support Global Accelerator. However, it will definitely be supported in the future.

**Comment by wolfgangzhu** [comment]
> Hello,
> 
> it seems that the support for Global Accelerator [resource is missing](https://registry.terraform.io/providers/zenlayer/zenlayercloud/latest/docs). Do you have any plan on the roadmap to add support for it?
> 
> Thanks!

We plan to support Global Accelerator in the first quarter.
